<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class AltohamiAccountSeeder extends Seeder
{
    /**
     * Imported chart of accounts from a legacy clinic finance system,
     * rebuilt from scratch under the five main accounts: الاصول,
     * الالتزامات, حقوق الملكية, الايرادات, المصروفات.
     *
     * The source export only carried a flat code/name/description with no
     * account type, and several codes were duplicated or malformed. Types
     * were inferred from each branch's top-level Arabic category, duplicate
     * codes were suffixed with the source row id to stay unique, one fully
     * duplicate row was dropped, and every account that used to sit at the
     * top level now hangs off the matching main account instead.
     *
     * This wipes the existing `accounts` table before reseeding, so any
     * journal entries, opening balances, or petty cash records that still
     * reference the old account ids will be left pointing at deleted rows.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Account::truncate();
        Schema::enableForeignKeyConstraints();

        $rows = [
            ['code' => '1', 'name' => 'الاصول', 'type' => 'asset', 'sub_type' => null, 'parent' => null],
            ['code' => '1.0.1', 'name' => 'الاصول الثابتة', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.2', 'name' => 'السيارات', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.1', 'name' => 'الاراضي', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.0.2', 'name' => 'الاصول المتداولة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.1', 'name' => 'نقدية بالبنوك', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.1.1', 'name' => 'بنك الخرطوم 2429365', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.1'],
            ['code' => '1.2.1.2', 'name' => 'بنك الخرطوم 1823762', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.1'],
            ['code' => '1.2.1.3', 'name' => 'بنك الخرطوم العام', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.1'],
            ['code' => '1.2.1.4', 'name' => 'بنك امدرمان الوطني', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.1'],
            ['code' => '1.2.2', 'name' => 'نقدية بالخزينة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.3', 'name' => 'ارصدة مدينة اخرى', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.4', 'name' => 'مسحوبات ملاك', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.4.1', 'name' => 'معتصم', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.4'],
            ['code' => '1.2.4.2', 'name' => 'حافظ', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.4'],
            ['code' => '1.2.5', 'name' => 'شركات التامين الطبي', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.6', 'name' => 'مصروفات مدفوعة مقدما', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.7', 'name' => 'مخزونات مواد وتجهيزات العمليات', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.3.1', 'name' => 'سلفيات', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.2', 'name' => 'عهد', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.8', 'name' => 'ايرادات مستحقة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '4', 'name' => 'الايرادات', 'type' => 'revenue', 'sub_type' => null, 'parent' => null],
            ['code' => '1.3.1.0.1', 'name' => 'ايراد العمليات والتنويم', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.2', 'name' => 'ايراد العيادات والخدمات', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.3', 'name' => 'ايراد المعمل', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.1', 'name' => 'الايرادات النقدية', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.1.1', 'name' => 'ايراد عمليات النساء والتوليد', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.1'],
            ['code' => '1.3.1.1.2', 'name' => 'ايراد عمليات الجراحة العامة', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.1'],
            ['code' => '1.3.1.1.3', 'name' => 'ايراد عمليات المسالك البولية والكلى', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.1'],
            ['code' => '1.3.1.4', 'name' => 'ايراد عمليات المخ والاعصاب', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.5', 'name' => 'ايراد عمليات انف واذن وحنجرة', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.6', 'name' => 'ايراد عمليات العظام', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.7', 'name' => 'ايراد عمليات التجميل', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.8', 'name' => 'ايراد عنابر الطابق الاول', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.9', 'name' => 'ايراد تنويم الغرف', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.10', 'name' => 'ايراد مستلزمات العمليات', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.11', 'name' => 'ايراد عمليات المناظير', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.3.1.11-36', 'name' => 'ايرادات  أخرى', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '5', 'name' => 'المصروفات', 'type' => 'expense', 'sub_type' => null, 'parent' => null],
            ['code' => '1.4.1', 'name' => 'تكلفة الايرادات', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.4.1.1', 'name' => 'اجور النسا والتوليد', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1'],
            ['code' => '1.4.1.1.1', 'name' => 'أجور أعضاء العمليات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1'],
            ['code' => '1.4.1.1.1.2', 'name' => 'أجور الجراحة العامة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.3', 'name' => 'اجور المسالك البولية والكلى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.4', 'name' => 'اجور المخ والاعصاب', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.5', 'name' => 'اجور الانف والاذن والحنجرة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.6', 'name' => 'اجور عمليات العظام', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.7', 'name' => 'اجور عمليات التجميل', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.4.1.1.1.8', 'name' => 'اجور عمليات المناظير', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.1.1'],
            ['code' => '1.6.1.13.12', 'name' => 'أجور مواد ومستلزمات العمليات', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.6.1.1', 'name' => 'المصروفات التشغيلية', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.6.1.1.12.1', 'name' => 'أيجار معدات وادوات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.12.2', 'name' => 'مواد وتجهيزات العمليات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.12.3', 'name' => 'صيانة اجهزة ومعدات العمليات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.2.6-51', 'name' => 'مخزونات مواد المعمل', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.2.7.1', 'name' => 'مخزونات مواد التخدير', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.7'],
            ['code' => '1.2.7.2', 'name' => 'مخزونات مواد التحضير', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.7'],
            ['code' => '1.5.1', 'name' => 'المشتريات', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.5.1.1', 'name' => 'مشتريات مواد التخدير', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.2', 'name' => 'مشتريات مواد التحضير', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.3', 'name' => 'مشتريات مواد المعمل', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.4', 'name' => 'مشتريات لوازم التمريض', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.5', 'name' => 'مشتريات لوازم العملية الصغيرة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.6', 'name' => 'مشتريات لوازم الايكو', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.7', 'name' => 'مشتريات لوازم اي سي جي', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.8', 'name' => 'مشتريات لوازم النظافة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.5.1.9', 'name' => 'مشتريات عامة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.4.1.1-64', 'name' => 'تكلفة ايرادات العمليات والتنويم', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1'],
            ['code' => '1.5.1.10', 'name' => 'مشتريات لوازم العيادات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.6.1.1.2', 'name' => 'اجور ورديات العيادات والتمريض', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.3', 'name' => 'تعبئة الاكسجين', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.4', 'name' => 'ترحيل الاكسجين', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.5', 'name' => 'جازولين المولد', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.6', 'name' => 'ترحيل جازولين المولد', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.7', 'name' => 'مصروفات تشغيلية عامة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.8', 'name' => 'مصروف استحقاقات تامين', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.2', 'name' => 'المصروفات عمومية وادارية', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.6.1.2.1', 'name' => 'الكهرباء', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.2', 'name' => 'أجور النظافة الاضافية', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2..3', 'name' => 'الضيافة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.4', 'name' => 'ترحيلات ومواصلات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.5', 'name' => 'ايجار المبنى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.6', 'name' => 'تصوير ومطبوعات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.7', 'name' => 'ادوات مكتبية', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.1.1', 'name' => 'أجور ورديات المعمل', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.2.8', 'name' => 'صيانة كهرباء المبنى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.9', 'name' => 'مصروف اهلاك الاصول الثابتة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.10', 'name' => 'تبرعات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.11', 'name' => 'مصروفات اخرى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.12', 'name' => 'رصيد هاتف', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.13', 'name' => 'صيانة سباكة المبنى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.1.9', 'name' => 'صيانة المولد', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.1.10', 'name' => 'صيانة المكيفات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.4.1.2', 'name' => 'تكلفة ايراد اخرى', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1'],
            ['code' => '1.4.1.2.1', 'name' => 'خصم مسموح به', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.2'],
            ['code' => '1.4.1.2.2', 'name' => 'مرتجع سدادات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.2'],
            ['code' => '1.4.1.2.3', 'name' => 'فروقات استقبال', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.4.1.2'],
            ['code' => '1.6.1.2.14', 'name' => 'وقود الادارة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.1.11', 'name' => 'أجور عمال', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.1'],
            ['code' => '1.6.1.2.15', 'name' => 'حوافز', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.16', 'name' => 'المرتبات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.16.1', 'name' => 'مرتبات قسم الامن والنظافة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.6.1.2.16.2', 'name' => 'مرتبات قسم الاستقبال والاحصاء', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.6.1.2.16.3', 'name' => 'مرتبات الكوادر الطبية', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.6.1.2.16.4', 'name' => 'مرتبات التمريض', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.6.1.2.16.5', 'name' => 'مرتبات الادارة المالية - الادارية', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.6.1.2.17', 'name' => 'اجر اضافي', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.18', 'name' => 'رسوم حكومية', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.2.19', 'name' => 'رسوم نفايات', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.6.1.3', 'name' => 'المصروفات التسويقية', 'type' => 'expense', 'sub_type' => null, 'parent' => '5'],
            ['code' => '1.6.1.3.1', 'name' => 'الدعاية والاعلان', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.3'],
            ['code' => '1.6.1.3.2', 'name' => 'الترويج', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.3'],
            ['code' => '2', 'name' => 'الالتزامات', 'type' => 'liability', 'sub_type' => null, 'parent' => null],
            ['code' => '1.7.1.1', 'name' => 'التزامات طويلة الاجل', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '2'],
            ['code' => '1.7.1.1.1', 'name' => 'موردون الاصول الثابتة', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1'],
            ['code' => '1.7.1.2', 'name' => 'التزامات متداولة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '2'],
            ['code' => '1.7.1.2.1', 'name' => 'الموردون', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2'],
            ['code' => '1.7.1.2.1.1', 'name' => 'موردون مستلزمات العمليات', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2.1.3', 'name' => 'موردون مواد المعمل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2.1.2', 'name' => 'موردون لوازم التمريض', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2.1.4', 'name' => 'موردون لوازم العملية الصغيرة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2.1.5', 'name' => 'موردون لوازم ايكو', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2..1.6', 'name' => 'موردون لوازم اي سي جي', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.1.2', 'name' => 'قروض', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1'],
            ['code' => '1.7.1.2.1.7', 'name' => 'موردون عامون', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1'],
            ['code' => '1.7.1.2.2', 'name' => 'دائنون حكوميون', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2'],
            ['code' => '1.7.1.2.2.1', 'name' => 'ديوان الضرائب', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.2'],
            ['code' => '1.7.1.2.2.2', 'name' => 'صندوق الضمان الاجتماعي', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.2'],
            ['code' => '1.2.5.15', 'name' => 'ديوان الزكاة- تامين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.7.1.2.3', 'name' => 'أرصدة دائنة اخرى', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2'],
            ['code' => '1.7.1.2.3.1', 'name' => 'ضريبة ارباح الاعمال المستحقة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.2', 'name' => 'ضريبة الدخل الشخصي المستحقة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.3', 'name' => 'الزكاة المستحقة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.4', 'name' => 'مصروفات مستحقة', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.5', 'name' => 'استحقاقات المرتبات', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.6', 'name' => 'مصروف استحقاق اجور اطباء العمليات', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.7', 'name' => 'ايرادات محصلة مقدما', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.8', 'name' => 'دائنون آخرون', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '3', 'name' => 'حقوق الملكية', 'type' => 'equity', 'sub_type' => null, 'parent' => null],
            ['code' => '1.8.1.1', 'name' => 'جاري المالك', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.8.1.2', 'name' => 'راس المال', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.8.1.3', 'name' => 'صافي الدخل', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.8.1.3-141', 'name' => 'ارباح محتجزة', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.8.1.5', 'name' => 'ارباح موزعة', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.8.1.5-143', 'name' => 'احتياطي', 'type' => 'equity', 'sub_type' => null, 'parent' => '3'],
            ['code' => '1.6.1.2.20', 'name' => 'الضمان تحمل الشركة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.3.1.2..1', 'name' => 'ايراد فتح ملف العمليات', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.2', 'name' => 'صافي ايراد عيادات الاطباء', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.3', 'name' => 'اجمالي ايراد العنبر', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.4', 'name' => 'ايراد العملية الصغيرة', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.5', 'name' => 'صافي ايراد الايكو', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.6', 'name' => 'صافي ايراد اي سي جي', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.7', 'name' => 'صافي ايراد الموجات الصوتية', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.2.7-153', 'name' => 'مخزونات اخرى', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.0.3', 'name' => 'الاصول غير الملموسة', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.0.3.1', 'name' => 'مشروعات تحت التنفيذ', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1.0.3'],
            ['code' => '1.3.1.2-158', 'name' => 'ايرادات التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '4'],
            ['code' => '1.6.1.2.15.1', 'name' => 'حوافز عامة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.15'],
            ['code' => '1.2.5.1', 'name' => 'مشروع التعدين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.2', 'name' => 'مصفاة الخرطوم', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.3', 'name' => 'برايم هيلث كير', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.4', 'name' => 'المتخصصة للتامين الطبي', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.5', 'name' => 'الحزمة الاضافية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.6', 'name' => 'سي اي سي هيلث كير', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.7', 'name' => 'القوات المسلحة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.8', 'name' => 'شركة النيلين للتامين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.9', 'name' => 'شركة زين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.10', 'name' => 'تامين - بنك ام درمان الوطني', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.11', 'name' => 'شركة بترولاينز', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.7.1.2.3.9', 'name' => 'استحقاقات المناظير', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.3.10', 'name' => 'استحقاق اشعة carm', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.1.2.1', 'name' => 'شركة الاقبال للغاز', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.2'],
            ['code' => '1.7.1.2.1.1.1', 'name' => 'شركة ريتا للاجهزة والمعدات الطبية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.7.1.2.3.11', 'name' => 'استحقاق منظار جراحي', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.3'],
            ['code' => '1.7.1.2.1.7.1', 'name' => 'الشذى للدعاية والاعلان', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.7'],
            ['code' => '1.2.3.1.1', 'name' => 'احمد فيصل سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.2.3.2.1', 'name' => 'عهدة - مهند', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.1.2', 'name' => 'شول نظافة - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.1.3', 'name' => 'المكيفات', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.2.3.1.3', 'name' => 'قرنق دينق - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.2.3.1.4', 'name' => 'محمد الحسن امن - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.6.1.2.16-183', 'name' => 'ايجار البيت', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.7.1.2.1.3.1', 'name' => 'شركة لجين - مواد معمل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.7.1.2.1.3.2', 'name' => 'شركة الاتمان - مواد معمل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.7.1.2.1.7.2', 'name' => 'مكتبة وائل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.7'],
            ['code' => '1.7.1.2.1.7.3', 'name' => 'مكتبة الزهراء', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.7'],
            ['code' => '1.7.1.2.1.1.2', 'name' => 'اعمال عدن التجارية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.2.4-189', 'name' => 'خزينة نقد اجنبي', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1'],
            ['code' => '1.7.1.1.1.1', 'name' => 'شركة تباشير الطبية', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1.1'],
            ['code' => '1.7.1.2.1.3.3', 'name' => 'شركة فلو ميديكال - مواد معمل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.2.3.1.5', 'name' => 'سلفية - بيبو', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.2.3.1.6', 'name' => 'جعفر - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.1.4', 'name' => 'سيبيا التور', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.7.1.1.1.2', 'name' => 'شركة ايباميد الطبية', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1.1'],
            ['code' => '1.2.3.1.7', 'name' => 'سلفية - سلوان صلاح', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.2.3.1.8', 'name' => 'سلفيةاسراء عبدالراق  - فاطمة الامين سابقا', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.5.1.11', 'name' => 'مشتريات لوازم المناظير', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.5.1'],
            ['code' => '1.2.3.1.9', 'name' => 'سلفية ادم نظافة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.1'],
            ['code' => '1.2.3.2.0', 'name' => 'سلفية - عمرو الطاهر', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.1-201', 'name' => 'سلفية - هارون نظافة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.2', 'name' => 'سلفية - نهلة نمر', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.3', 'name' => 'هنية - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.4', 'name' => 'سلفية سعيد', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.5', 'name' => 'سلفية علا', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.6', 'name' => 'سلفية - نهال ميترون', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.7', 'name' => 'سلفية - عاصم', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.8', 'name' => 'سلفية - وئام', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.3.2.9', 'name' => 'سلفية - جمانة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.1.5', 'name' => 'بطارية usp كمبيوتر المدير المالي', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.7.1.2.1.1.3', 'name' => 'باقرين الطبية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.2.3.3.0', 'name' => 'مجاهد امن - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.1', 'name' => 'نسيبة عمر - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.2', 'name' => 'عمر الطيب - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.3', 'name' => 'محمد مجدي - معمل - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.1.6', 'name' => 'مضخة مياه', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.7.1.1.1.3', 'name' => 'شركة مرواكو', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1.1'],
            ['code' => '1.7.1.2.1.7.4', 'name' => 'شركة ديمارا لمواد التنظيف', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.7'],
            ['code' => '1.2.3.3.4', 'name' => 'كمال - امن سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.5', 'name' => 'دينق  - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.7.1.1.1.4', 'name' => 'شركة ماتريكس', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1.1'],
            ['code' => '1.1.7', 'name' => 'مونيتر - ماتريكس', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.8', 'name' => 'احواض غسيل - اصول', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.9', 'name' => 'اطقم جراحية للعمليات -  معدات و ادوات', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.7.1.2.1.1.4', 'name' => 'المهندس الطبية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.7.1.2.1.1.5', 'name' => 'شركة عمر عبدالرحمن', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.1.10', 'name' => 'منظم كهرباء السي ارم', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.2.4.3', 'name' => 'منتصر', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.4'],
            ['code' => '1.2.5.12', 'name' => '- تامين / شركة البركة للتامين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.13', 'name' => 'شركة 2بي', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.14', 'name' => 'شركة سوداتل - تامين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.15-232', 'name' => 'شركة المتحدة - تامين', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.7.1.2.1.3.4', 'name' => 'شركة اوماك الطبية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.2.3.3.6', 'name' => 'نسيبة قسم السيد - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.1.11', 'name' => 'جهاز فلتر مياه العمليات', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.2.5.16', 'name' => 'المواصفات والمقاييس', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.6.1.2.17-237', 'name' => 'منح الاعياد', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.2.3.3.7', 'name' => 'عبدالله سلفية ممرض', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.0.3.1.1', 'name' => 'المحول الكهربائي', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1.0.3.1'],
            ['code' => '1.1.12', 'name' => 'مايكروسكوب', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.0.3.1.2', 'name' => 'معمل المايكرو', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1.0.3.1'],
            ['code' => '1.2.3.3.8', 'name' => 'امجد معمل - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.7.1.2.1.1.5-243', 'name' => 'شركة جيد لمستلزمات العمليات', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.7.1.2.1.1.6', 'name' => 'شركة نعم الطبية لمواد التخدير', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.2.3.3.9', 'name' => 'عثمان امن - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.1.13', 'name' => 'اشراف اداري  -لابتوب', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.14', 'name' => 'طابعة معمل المايكرو', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.1.15', 'name' => 'ثلاجة معمل المايكرو', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.2.3.3.10', 'name' => 'جهاد المعمل - نجود سابقا', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.1.16', 'name' => 'ثلاجات غرف صغيرة 8', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.2.3.3.11', 'name' => 'بدل اجازات', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.1.17', 'name' => 'بطاطير التور والاشعة', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.6.1.2.16-253', 'name' => 'حافز غلاء معيشة', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2'],
            ['code' => '1.1.18', 'name' => 'جهاز لاقشور امريكي', 'type' => 'asset', 'sub_type' => 'non_current', 'parent' => '1'],
            ['code' => '1.7.1.1.1.5', 'name' => 'شركة اعمار', 'type' => 'liability', 'sub_type' => 'long_term', 'parent' => '1.7.1.1.1'],
            ['code' => '1.7.1.2.1.7.6', 'name' => 'نوكيا الخليج', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.7'],
            ['code' => '1.2.3.3.12', 'name' => 'الباقر - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.2.2-258', 'name' => 'جزاءات', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3.2'],
            ['code' => '1.2.5.17', 'name' => 'القضائية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.2.5.18', 'name' => 'شركة زادنا العالمية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.5'],
            ['code' => '1.6.1.2.16.6', 'name' => 'ض الدخل الشخصي', 'type' => 'expense', 'sub_type' => null, 'parent' => '1.6.1.2.16'],
            ['code' => '1.7.1.2.1.3.5', 'name' => 'شركة بيتاي', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.7.1.2.1.1.7', 'name' => 'شركة بيتاي', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.7.1.2.1.1.8', 'name' => 'شركة اكسلانس', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.1'],
            ['code' => '1.7.1.2.1.3.6', 'name' => 'الهشاب لاب', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.7.1.2.1.3.7', 'name' => 'المشرق للاجهزة الطبية', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.7.1.2.1.2.2', 'name' => 'مصنع سيشوان', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.2'],
            ['code' => '1.7.1.2.1.3.7-268', 'name' => 'اوميقا كير لمواد المعمل', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.3.1.2.1', 'name' => 'ايرادات المعمل التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.2-270', 'name' => 'صافي ايراد الايكو - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.3-271', 'name' => 'ايراد الموجات الصوتية - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.4-272', 'name' => 'صافي ecg تامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.5-273', 'name' => 'صافي العملية الصغيرة - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.6-274', 'name' => 'صافي عيادات الاطباء - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.7-275', 'name' => 'صافي ايراد التنويم الباطني - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.8', 'name' => 'ايراد العمليات الجراحية - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.3.1.2.9', 'name' => 'ايراد المناظير العلاجية - التامين', 'type' => 'revenue', 'sub_type' => null, 'parent' => '1.3.1.2'],
            ['code' => '1.7.1.2.1.2.3', 'name' => 'البلاد', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.2'],
            ['code' => '1.7.1.2.1.3.8', 'name' => 'ابو احمد', 'type' => 'liability', 'sub_type' => 'current', 'parent' => '1.7.1.2.1.3'],
            ['code' => '1.2.3.3.13', 'name' => 'سلفية محمد حاتم', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.14', 'name' => 'محمد عبدالرحيم - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.15', 'name' => 'سلفية خولة', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.15-283', 'name' => 'سلفية احمد حسن معمل', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.16', 'name' => 'سلفية عبدالرحمن', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.17', 'name' => 'صفاء تمريض - سلفية', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
            ['code' => '1.2.3.3.18', 'name' => 'يسرا سلفية تمريض', 'type' => 'asset', 'sub_type' => 'current', 'parent' => '1.2.3'],
        ];

        $ids = [];

        foreach ($rows as $row) {
            $parentId = $row['parent'] ? ($ids[$row['parent']] ?? null) : null;

            $account = Account::updateOrCreate(
                ['code' => $row['code']],
                [
                    'name' => $row['name'],
                    'type' => $row['type'],
                    'sub_type' => $row['sub_type'],
                    'parent_id' => $parentId,
                    'is_active' => true,
                ]
            );

            $ids[$row['code']] = $account->id;
        }
    }
}
